services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: base64:463YufQ4LODjc6oF/1mb+Ine5qCa94XCXPb0yNaHu/U=
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: E7649aksl
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - .:/opt
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        networks:
            - laravel_network

    db:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: E7649aksl
            MYSQL_DATABASE: laravel
        ports:
            - "3307:3306" # Ensure this is correct as needed
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

    redis:
        image: redis:alpine
        container_name: redis_server
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - laravel_network

volumes:
    mysql_data:
    redis_data:

networks:
    laravel_network:
        driver: bridge
